---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: typeform.templates.krateo.io
spec:
  compositeTypeRef:
    apiVersion: templates.krateo.io/v1alpha1
    kind: TypeForm
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-k8s-pc-in"
      readinessChecks:
        - type: None
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                namespace: krateo-system
              spec:
                project: default
                source:
                  targetRevision: HEAD
                  path: chart
                destination:
                  server: https://kubernetes.default.svc
                  namespace: krateo-system
                syncPolicy:
                  automated:
                    prune: true
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "spec.forProvider.manifest.metadata.labels[deploymentId]"
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-argocd-app-object"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-k8s-pc-in"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.toRepo.schema"
              - fromFieldPath: "spec.toRepo.domain"
              - fromFieldPath: "spec.toRepo.organizationName"
              - fromFieldPath: "spec.toRepo.repositoryName"
            strategy: string
            string:
              fmt: "%s://%s/%s/%s"
          toFieldPath: "spec.forProvider.manifest.spec.source.repoURL"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.manifest.spec.destination.namespace"
    - base:
        apiVersion: git.krateo.io/v1alpha1
        kind: ProviderConfig
        spec:
          deploymentServiceUrl: http://deployment-service-service.krateo-system.svc
          fromRepoCredentials:
            authMethod: basic
            source: Secret
            secretRef:
              namespace: krateo-system
              key: token
          toRepoCredentials:
            authMethod: basic
            source: Secret
            secretRef:
              namespace: krateo-system
              key: token
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-provider-git-pc"
        - fromFieldPath: "spec.fromRepo.domain"
          toFieldPath: "spec.fromRepoCredentials.secretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-secret"
        - fromFieldPath: "spec.toRepo.domain"
          toFieldPath: "spec.toRepoCredentials.secretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-secret"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.deploymentServiceUrl"
          transforms:
            - type: string
              string:
                fmt: "http://deployment-service-service.%s.svc"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.fromRepoCredentials.secretRef.namespace"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.toRepoCredentials.secretRef.namespace"
    - base:
        apiVersion: git.krateo.io/v1alpha1
        kind: Repo
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.fromRepo.schema"
              - fromFieldPath: "spec.fromRepo.domain"
              - fromFieldPath: "spec.fromRepo.organizationName"
              - fromFieldPath: "spec.fromRepo.repositoryName"
            strategy: string
            string:
              fmt: "%s://%s/%s/%s"
          toFieldPath: "spec.forProvider.fromRepo.url"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.toRepo.schema"
              - fromFieldPath: "spec.toRepo.domain"
              - fromFieldPath: "spec.toRepo.organizationName"
              - fromFieldPath: "spec.toRepo.repositoryName"
            strategy: string
            string:
              fmt: "%s://%s/%s/%s"
          toFieldPath: "spec.forProvider.toRepo.url"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-git-pc"
    - base:
        apiVersion: github.krateo.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: krateo-system
              key: token
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-provider-github-pc"
        - fromFieldPath: "spec.toRepo.domain"
          toFieldPath: "spec.credentials.secretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-secret"
        - fromFieldPath: "spec.toRepo.apiUrl"
          toFieldPath: "spec.apiUrl"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.credentials.secretRef.namespace"
    - base:
        apiVersion: github.krateo.io/v1alpha1
        kind: Repo
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: "spec.toRepo.organizationName"
          toFieldPath: "spec.forProvider.org"
        - fromFieldPath: "spec.toRepo.repositoryName"
          toFieldPath: "spec.forProvider.name"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-github-pc"
    - base:
        apiVersion: typeform.krateo.io/v1alpha1
        kind: ProviderConfig
        spec:
          verbose: false
          credentials:
            source: Secret
            secretRef:
              namespace: krateo-system
              name: typeform.com-secret
              key: token
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-provider-typeform-pc"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.logServiceUrl"
          transforms:
            - type: string
              string:
                fmt: "http://log-service-service.%s.svc"
        - fromFieldPath: "spec.toRepo.domain"
          toFieldPath: "spec.credentials.secretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-secret"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.credentials.secretRef.namespace"
    - base:
        apiVersion: typeform.krateo.io/v1alpha1
        kind: Form
      patches:
        - fromFieldPath: "metadata.labels[deploymentId]"
          toFieldPath: "metadata.labels[deploymentId]"
        - fromFieldPath: "spec.form.title"
          toFieldPath: "spec.forProvider.title"
        - fromFieldPath: "spec.form"
          toFieldPath: "spec.forProvider"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-typeform-pc"
