---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: typeform.templates.krateo.io
spec:
  group: templates.krateo.io
  names:
    kind: TypeForm
    plural: typeform
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                namespace:
                  description: Kubernetes namespace for Krateo, i.e. krateo-system
                  type: string
                fromRepo:
                  type: object
                  properties:
                    domain:
                      type: string
                    provider:
                      type: string
                    apiUrl:
                      type: string
                    repositoryName:
                      type: string
                    organizationName:
                      type: string
                    schema:
                      type: string
                toRepo:
                  type: object
                  properties:
                      domain:
                        type: string
                      provider:
                        type: string
                      apiUrl:
                        type: string
                      repositoryName:
                        type: string
                      organizationName:
                        type: string
                      schema:
                        type: string
                _values:
                  description: Typeform Form template values
                  type: string
                form:
                  description: Typeform
                  type: object
