---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: typeform.templates.krateo.io
spec:
  group: templates.krateo.io
  names:
    kind: TypeForm
    plural: typeform
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                dashboard:
                  description: elements for Krateo UI
                  type: object
                namespace:
                  description: Kubernetes namespace for Krateo, i.e. krateo-system
                  type: string
                fromRepo:
                  type: object
                  properties:
                    domain:
                      type: string
                    provider:
                      type: string
                    apiUrl:
                      type: string
                    repositoryName:
                      type: string
                    organizationName:
                      type: string
                    schema:
                      type: string
                toRepo:
                  type: object
                  properties:
                      domain:
                        type: string
                      provider:
                        type: string
                      apiUrl:
                        type: string
                      repositoryName:
                        type: string
                      organizationName:
                        type: string
                      schema:
                        type: string
                _values:
                  description: Typeform Form template values
                  type: string
                form:
                  description: Typeform
                  type: object
                  properties:
                    title:
                      description: Typeform title
                      type: string
                    welcomeScreens:
                      description: Typeform welcomeScreens
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          layout:
                            type: object
                            properties:
                              type:
                                type: string
                              attachment:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  href:
                                    type: string
                          properties:
                            type: object
                            properties:
                              buttonText:
                                type: string
                              showButton:
                                type: boolean
                    thankyouScreens:
                      description: Typeform thankyouScreens
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          layout:
                            type: object
                            properties:
                              type:
                                type: string
                              attachment:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  href:
                                    type: string
                          properties:
                            type: object
                            properties:
                              shareIcons:
                                type: boolean
                              showButton:
                                type: boolean
                    fields:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          title:
                            type: string
                          properties:
                            type: object
                            properties:
                              description:
                                type: string
                              shape:
                                type: string
                              steps:
                                type: integer
                          validations:
                            type: object
                            properties:
                              required:
                                type: boolean
                          layout:
                            type: object
                            properties:
                              type:
                                type: string
                              attachment:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  href:
                                    type: string
